//  let Bank=require("./Bank").Bank;

// let bank=new Bank(3569,10);
// let calc=bank.interest_concept();
// if(calc.interest>351)
// {
//   console.log("The amount generated by interest is: USD "+calc.interest+" exceeds USD 351");  
// }
// else
// {
//   console.log("The amount generated by interest is: USD "+calc.interest+" does not exceeds USD 351");  
// }
 
// console.log("                                              ");
// console.log("The balance generated in the account is: USD "+calc.balanced_generated);



